name: 'Flyway Migrate'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Postgres JDBC Driver
        run: |
          wget -O postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.5.jar
      
      - name: Run Flyway Migration
        run: |
          mkdir -p drivers migrations
          mv postgresql.jar drivers/
          mv *.sql migrations/
          docker run --rm \
            -v ${{ github.workspace }}/drivers:/flyway/drivers \
            -v ${{ github.workspace }}/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url=${{ secrets.FLYWAY_URL }} \
            -user=${{ secrets.FLYWAY_USER }} \
            -password=${{ secrets.FLYWAY_PASSWORD }} \
            migrate
